apiVersion: secrets-store.csi.x-k8s.io/v1
kind: SecretProviderClass
metadata:
  name: azure-team3kv-user-msi
spec:
  provider: azure
  parameters:
    usePodIdentity: "false"
    useVMManagedIdentity: "true" # Set to true for using managed identity
    userAssignedIdentityID: a1d94381-5751-4881-a0bf-dd994b62313c # Set the clientID of the user-assigned managed identity to use
    keyvaultName: team3akskeyvault # Set to the name of your Azure Key Vault instance
    cloudName: "" # [OPTIONAL for Azure] if not provided, azure environment will default to AzurePublicCloud
    objects: |
      array:
        - |
          objectName: SQLServer
          objectType: secret              # object types: secret, key or cert
          objectVersion: ""               # [OPTIONAL] object versions, default to latest if empty
          objectAlias: SQL_SERVER
        - |
          objectName: SQLServerPassword
          objectType: secret
          objectVersion: ""
          objectAlias: SQL_PASSWORD
        - |
          objectName: SQLServerUserName
          objectType: secret
          objectVersion: ""
          objectAlias: SQL_USER
    tenantId: e128dcfb-da2f-4697-9582-ee75a859925d
