apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web
  labels:
    app: tripviewer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
        - name: tripviewer
          image: registryvpg9012.azurecr.io/tripinsights/tripviewer:1.0
          env:
            - name: USERPROFILE_API_ENDPOINT
              value: http://userprofile.api
            - name: TRIPS_API_ENDPOINT
              value: http://trips.api
          ports:
            - containerPort: 80
